### ISSUE TITLE
[DOC] Expand Quickstart documentation to include Trino examples

### ISSUE THREAD

**Issue by annafil** [apache/polaris#13]
Because Polaris Catalog is built on top of Apache Iceberg's REST protocol, it should [natively support Trino's Iceberg connector.](https://trino.io/docs/current/connector/iceberg.html)

**Comment by annafil** [comment]
Is being worked on in https://github.com/polaris-catalog/polaris/pull/44

**Comment by eric-maynard** [comment]
We now have these docs [here](https://github.com/apache/polaris/tree/main/getting-started/trino), so I'm closing this out 👍
