### ISSUE TITLE
[FEATURE REQUEST] Switch the tests against EclipseLink with H2 database

### ISSUE THREAD

**Issue by aihuaxu** [apache/polaris#149]
### Is your feature request related to a problem? Please describe.

Currently, the tests are tested against InMemoryPolarisMetaStoreManagerFactory and PolarisTreeMapMetaStoreSessionImpl implementation only and only a unit test is covering for EclipseLinkPolarisMetaStoreManagerFactory. To be closer to the production with database backed EclipseLinkPolarisMetaStoreManagerFactory and PolarisEclipseLinkMetaStoreSessionImpl, we should also consider adding all the tests against EclipseLinkPolarisMetaStoreManagerFactory.

**Comment by TomerHeber** [comment]
I think the tests are running against h2 (in addition to the memory variant).
At least, that's what I'm observing.

For example, if you remove h2 from gradle (testImplementation), the tests will fail.

**Comment by aihuaxu** [comment]
> I think the tests are running against h2 (in addition to the memory variant). At least, that's what I'm observing.
> 
> For example, if you remove h2 from gradle (testImplementation), the tests will fail.

Currently there is a unit test which test against H2 but not regression tests.  I think it would good to test H2 for regression tests as well.
