### ISSUE TITLE
[FEATURE REQUEST] Trino getting started docker compose

### ISSUE THREAD

**Issue by collado-mike** [apache/polaris#22]
**Is your feature request related to a problem? Please describe.**

It would be great to have a docker-compose setup for Trino as we do for Spark

**Describe the solution you'd like**
A docker-compose setup with Trino and Polaris

**Comment by kevinjqliu** [comment]
@collado-mike I can take a look at this. 

Is the Spark setup referred to here the [quickstart](https://github.com/polaris-catalog/polaris/blob/main/docs/quickstart.md#connecting-with-spark) doc?

**Comment by collado-mike** [comment]
> @collado-mike I can take a look at this. 
> 
> 
> 
> Is the Spark setup referred to here the [quickstart](https://github.com/polaris-catalog/polaris/blob/main/docs/quickstart.md#connecting-with-spark) doc?
> 

Yeah, that's what I was thinking of.

**Comment by kevinjqliu** [comment]
Great! I opened #42 for Trino. 
We can extend the same solution to Spark. It'll be nice to just docker-compose a Spark setup instead of installing Spark manually
