### ISSUE TITLE
[BUG] Create View command is failing with Spark console

### ISSUE THREAD

**Issue by nk1506** [apache/polaris#225]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

`spark-sql ()> create view db1.v1 as select * from db1.table1;

Catalog polaris does not support views.`

**Comment by ebyhr** [comment]
Does this issue happen even after https://github.com/apache/polaris/pull/216?

**Comment by nk1506** [comment]
@ebyhr ,Surprisingly, I’m still encountering this error with SparkCLI. I’m currently investigating it. I’m not sure how to assign this bug to myself. Could you help?

**Comment by collado-mike** [comment]
You need to enable Iceberg's spark extensions to create views: see https://github.com/apache/polaris/blob/main/regtests/t_pyspark/src/iceberg_spark.py#L97 for example configuration
