### ISSUE TITLE
[BUILD] Change repositories mode when using gradle init scripts

### ISSUE THREAD

**Issue by anuragmantri** [apache/polaris#265]
Polaris uses  [RepositoriesMode.FAIL_ON_PROJECT_REPOS](https://github.com/apache/polaris/blob/0a539dbd47a99d9c50ef3598d0ee8ee770a864ea/settings.gradle.kts#L66) setting for dependency management. For companies using gradle init scripts with internal repository declarations, this will fail to build with below error 

```
Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by initialization script '/Users/anurag/.gradle/init.gradle' 
```

Should we remove this mode or set it to [PREFER_SETTINGS](https://docs.gradle.org/current/javadoc/org/gradle/api/initialization/resolve/RepositoriesMode.html#PREFER_SETTINGS) instead? 

What are your thoughts @flyrain @aihuaxu ?

**Comment by flyrain** [comment]
I'm OK with that, as it will make it easy for companies to integrate with internal libs. Feel free to file an PR. Also, this is property is introduced by #53, cc @snazy for that.

**Comment by snazy** [comment]
I'm okay to remove the setting (use the default).

**Comment by jbonofre** [comment]
It makes sense to me. 👍

**Comment by aniket-s-kulkarni** [comment]
@jbonofre - https://github.com/apache/polaris/pull/434
