### ISSUE TITLE
[BUG] Typo in Copyright in https://polaris.apache.org/

### ISSUE THREAD

**Issue by dbosco** [apache/polaris#275]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

The `Copyright` in https://polaris.apache.org/ has a typo. It is `Copyyright`.

> **Copyyright** � 2024 The Apache Software Foundation, Licensed under the Apache License, Version 2.0.

### To Reproduce

1. Go to https://polaris.apache.org/
2. Check the bottom of the page

### Actual Behavior

This is what we have now:
> **Copyyright** � 2024 The Apache Software Foundation, Licensed under the Apache License, Version 2.0.

### Expected Behavior

It should be 
> **Copyright** � 2024 The Apache Software Foundation, Licensed under the Apache License, Version 2.0.

### Additional context

Given the instructions, I am happy to update it. Thanks

**Comment by dbosco** [comment]
Can this be assigned to me? Thanks.

**Comment by jbonofre** [comment]
This issue should have been created on the polaris-site repo.
