### ISSUE TITLE
[BUG] DefaultContextResolver is not using defaultRealm value from the PolarisApplicationConfig

### ISSUE THREAD

**Issue by almazgalievisl** [apache/polaris#281]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

[PolarisApplicationConfig](https://github.com/apache/polaris/blob/cc58730a0c626dba574c2577b32081b17b97b7a8/polaris-service/src/main/java/org/apache/polaris/service/config/PolarisApplicationConfig.java#L117) defines defaultRealm and allows overriding it trough configuration file. [DefaultContextResolver](https://github.com/apache/polaris/blob/cc58730a0c626dba574c2577b32081b17b97b7a8/polaris-service/src/main/java/org/apache/polaris/service/context/DefaultContextResolver.java#L52) ignores a value from the configuration. 

### To Reproduce

0. Setup an eclipse link with a database name which is different from `default-realm`
1. Set `defaultRealm`  in the configuration yaml file
2. Try to connect to get the token without setting `realm` explicitly in the request's headers
3. Polaris returns an error: 
```
FATAL: database 'default-realm' does not exist
```

### Actual Behavior

Configuration setting is not a source of truth for the all components

### Expected Behavior

Configuration setting defines a default value for the all components

**Comment by loicalleyne** [comment]
I came across the same issue, but since this error is thrown when the realm is incorrect or the bearer token is missing perhaps it could also indicate an attempt at unauthorized access. Either way the message returned could be clearer.
