### ISSUE TITLE
[BUG] CLI doesn't work when just providing --host

### ISSUE THREAD

**Issue by lrichards-etsy** [apache/polaris#345]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

When using a host where the port can be inferred the CLI still tries to put the default 8181 at the end, which makes the call error/hang.

### To Reproduce

`./polaris --host some.hosted.url --client-id <client-id> --client-secret <client-secret> catalogs list`

### Actual Behavior

Returns back `http://some.hosted.url:8181/api/management/v1` & `http://some.hosted.url:8181/api/catalog/v1`

### Expected Behavior

Expecting the urls to be `http://some.hosted.url/api/management/v1` & `http://some.hosted.url/api/catalog/v1`

### Additional context

The CLI code that needs updating is here - https://github.com/apache/polaris/blob/main/regtests/client/python/cli/polaris_cli.py#L110-L112

If a host is added but no port is given it should not try and use the default one.

**Comment by MonkeyCanCode** [comment]
@lrichards-etsy I think this is controlled by optional parameter `--port`. Here is the usage page:
```
./polaris --help
...
usage: polaris_cli.py [-h] [--host HOST] [--port PORT] [--client-id CLIENT_ID] [--client-secret CLIENT_SECRET]
                      [--access-token ACCESS_TOKEN]
                      {catalogs,principals,principal-roles,catalog-roles,privileges,namespaces} ...
```

This line set the default port to 8181: https://github.com/apache/polaris/blob/main/regtests/client/python/cli/options/parser.py#L41

Now back to the issue mentioned above, here will be the right command to use (assuming the target port to be 443):
```
./polaris --host some.hosted.url --port 443 --client-id <client-id> --client-secret <client-secret> catalogs list
```

**Comment by lrichards-etsy** [comment]
@MonkeyCanCode thanks for the reply! 

I can get the CLI working if I pass in the target port, but the host URL for the ingress service that I created for my K8 cluster can also be used without passing in the port and it was that pathway that I was trying to get to work. The only way it did was by removing the need for the port in the URL created by the CLI.

Wondering if just using the host without the port is a big enough use case to update the CLI code? Or if people think its too small to warrant a code update to handle it.

**Comment by MonkeyCanCode** [comment]
> @MonkeyCanCode thanks for the reply! 
> 
> I can get the CLI working if I pass in the target port, but the host URL for the ingress service that I created for my K8 cluster can also be used without passing in the port and it was that pathway that I was trying to get to work. The only way it did was by removing the need for the port in the URL created by the CLI.
> 
> Wondering if just using the host without the port is a big enough use case to update the CLI code? Or if people think its too small to warrant a code update to handle it. 
> 

I am not quite sure I am following. For k8s Ingress, you will only be able to use port 80 or 443 (don't think it is allowed to be changed). Now assuming we are using 443 and have a path that is mapped to the service 8181 for Polaris, you should still be able to access Polaris on port 443 via CLI when hitting the ingress instead of the pod directly. Maybe I am missing something here. Do you mind adding in a bit more details such as the sample ingress config etc.

**Comment by lrichards-etsy** [comment]
@MonkeyCanCode Sorry for the confusion. 

The following works fine - `./polaris --host some.hosted.url --port 80 --client-id <client-id> --client-secret <client-secret> catalogs list` for me. So this really isn't a bug anymore. 

What I was trying to explain (pretty badly 😆 ) is that the above creates a URL like so `http://some.hosted.url:80/api/catalog/v1` -- but the URL `http://some.hosted.url/api/catalog/v1` also works for talking to Polaris for my setup (which I've tested). The later configuration isn't supported in the CLI as it always need a port. I thought maybe it would be worth handling that use case, but passing in the post is fine. 

I'm fine with closing this bug report :)

**Comment by eric-maynard** [comment]
So the default port is 8181, but are you basically suggesting we should default to 80 if the host is provided?

I think we should still treat 8181 as the Polaris port; you can imagine using the CLI with two Polaris instances and wanting to connect to both but not wanting to have to specify a port.

**Comment by lrichards-etsy** [comment]
Closing this bug issue -- CLI works when a port is given.

**Comment by lrichards-etsy** [comment]
Closing this bug issue -- CLI works when a port is given.

**Comment by lrichards-etsy** [comment]
> So the default port is 8181, but are you basically suggesting we should default to 80 if the host is provided?

Defaulting to 8181 makes sense. I was suggesting a way to use the CLI if you had a URL where the port didn't need to be provided. Buts its all good. I've closed the bug and will pass in the port for our use case going forward.
