### ISSUE TITLE
[BUG] Credential vending not happening when remove_orphan_files in Spark

### ISSUE THREAD

**Issue by MonkeyCanCode** [apache/polaris#390]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

With proper settings, spark can fail on credential vending when performing `remove_orphan_files`. This seems to be related to https://github.com/apache/iceberg/pull/7914. 

Here is the slack thread for this discussion: https://apache-iceberg.slack.com/archives/C07HADW86HZ/p1729527019849439

Also, this operation works when using Trino with vended-credentials-enabled enabled.

### To Reproduce

1. Setup proper settings for Spark to work with Polaris
2. Ensure spark client can perform DDL/DML and couple data ops on Iceberg table based on settings from step 1
3. Perform remove_orphan_files within spark

### Actual Behavior

Spark will first reported `No FileSystem for scheme "s3"` as it is trying to use HadoopFileIO. After manually set the `spark.hadoop.fs.s3.impl` to `org.apache.hadoop.fs.s3a.S3AFileSystem`. If the client has S3 credential with needed access, it will work. However, if through credential vending from Polars, it can fail (in this case, client doesn't have S3 credential).

### Expected Behavior

Spark should use credential vending then perform remove_orphan_files and no manual specify of `spark.hadoop.fs.s3.impl` should be needed. 

### System information

Polaris version: latest
Iceberg version: 1.6.1
Spark version: 3.5.2

**Comment by collado-mike** [comment]
This is well-described in the linked Iceberg issue, but the TL;DR here is that Iceberg itself isn't using the credentials returned from Polaris. This isn't something we can fix on the Polaris side

**Comment by MonkeyCanCode** [comment]
Yes, understand. But it is something worth mentioning in our doc so people won't think credential vending will apply to all operations?

**Comment by collado-mike** [comment]
I think there's a lot missing in our docs about credential vending 😂

A doc update sounds good to me.

**Comment by MonkeyCanCode** [comment]
Thanks for confirmation. I will run some tests tomorrow to come up with a full list of ops that are not currently supported with credential vending then raise a PR for doc update.

**Comment by MonkeyCanCode** [comment]
Here is a sample PR for the purposed changes in doc: https://github.com/apache/polaris/pull/398

**Comment by MonkeyCanCode** [comment]
Close this one as the issue is in Apache Iceberg side and the doc for Apache Polaris had been updated to reflect which operation is not supposed via credentials vending.
