### ISSUE TITLE
[FEATURE REQUEST] Does the polaris CLI support the create table command?

### ISSUE THREAD

**Issue by horizonzy** [apache/polaris#507]
Looks like the Polaris CLI only supports create namespaces command, if I want to register a table in a catalog, how do I do?

**Comment by MonkeyCanCode** [comment]
@horizonzy currently the CLI mainly supported catalogs, namespaces, principals, principal-roles, catalog-roles and  privileges management. You can't register a table in a catalog with it as of now. I usually do this via spark/trino.

**Comment by horizonzy** [comment]
> @horizonzy currently the CLI mainly supported catalogs, namespaces, principals, principal-roles, catalog-roles and privileges management. You can't register a table in a catalog with it as of now. I usually do this via spark/trino/pyiceberg.

OK, make sense
