### ISSUE TITLE
[BUG] Misuse of technical IDs when creating entities

### ISSUE THREAD

**Issue by snazy** [apache/polaris#528]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

Implementations of operations that _create new_ entities, for example in `PolarisAdminService`, must always generate a _new_ technical ID and not use an _externally_ provided one.

Many places in the code base so something like this:
```java
  public PolarisEntity createCatalog(PolarisEntity entity) {
---
    long id =
        entity.getId() <= 0
            ? metaStoreManager.generateNewEntityId(getCurrentPolarisContext()).getId()
            : entity.getId();
...
    PolarisEntity polarisEntity =
        new PolarisEntity.Builder(entity)
            .setId(id)
            .setCreateTimestamp(System.currentTimeMillis())
            .build();
...
```

The above pattern is error prone and can easily lead to issues like ID collisions later on.

Such implementation must really ensure that
1. the passed in ID is either not present or a not-present value (0)
2. the ID of the new entity must always be generated

**Comment by jbonofre** [comment]
@snazy to be honest, I don't see the use case to use an external ID. I agree that the ID should be always generated:

```
.setId(metaStoreManager.generateNewEntityId(getCurrentPolarisContext()).getId())
```

and ignore the ID coming from the "new" entitiy.
