### ISSUE TITLE
Add NOTICE + LICENSE* as static resources to distributables

### ISSUE THREAD

**Issue by snazy** [apache/polaris#557]
### Describe the bug

The `NOTICE` + `LICENSE*` files should be included in executable artifacts of distributions, so the contents of these files can be
* printed to the console in CLI applications
* returned as static web resources

I.e. those resources need to be _programmatically accessible_.

**Comment by jbonofre** [comment]
Not the LICENSE from source distribution. It's already done in my PR

**Comment by snazy** [comment]
Maybe I wasn't clear in the description, but this issue is about having those resources available _programmatically_ and as static web resources, while #495 just adds these files to the zip/tar/etc

**Comment by jbonofre** [comment]
Ahh git it. I thought you mean adding the files in the archive. It makes sense.
