### ISSUE TITLE
Add Support for Proxy Settings to Connect to Snowflake Open Catalog Using Spark Connector in Java

### ISSUE THREAD

**Issue by sfc-gh-hdogra** [apache/polaris#569]
### Is your feature request related to a problem? Please describe.

The customer requested it for the following use case-

**Description:**

> Customers need the ability to configure proxy settings when connecting to Snowflake Open Catalog via the Spark Connector in Java. This is especially critical for organizations where network access to SaaS services (like Snowflake Open Catalog) is restricted and must go through a corporate proxy.
> 
> Currently, proxy configuration is supported for connecting to Snowflake accounts via the Snowflake Spark Connector, as documented here:
> [Proxy Options for Snowflake Spark Connector](https://docs.snowflake.com/en/user-guide/spark-connector-use#proxy-options).
> 
> However, similar proxy configuration options are not available when connecting to Snowflake Open Catalog. Attempts to use standard Spark configurations like spark.driver.extraJavaOptions to set proxy details have not been successful.

**Requested Enhancement:**

> Provide a way to configure proxy details when connecting to Snowflake Open Catalog using Spark in Java, similar to how proxy settings are specified for the Snowflake Spark Connector.

### Additional context

As requested by the engineering team, raising this FR for the issue.

**Comment by snazy** [comment]
@sfc-gh-hdogra This is the issue tracker for Apache Polaris, not for Snowflake's service offering, so closing this issue. This is not the right place for requests targeting closed source commercial offerings.
